Fix build error for Qt <= 6.8 (typo)
Build errored out on our buildmaster with this:
```
[ 13%] Building CXX object CMakeFiles/kolourpaint.dir/commands/imagelib/transforms/kpTransformSkewCommand.cpp.o
/sources/kolourpaint-25.12.0/commands/imagelib/transforms/kpTransformFlipCommand.cpp: In member function 'void kpTransformFlipCommand::flip()':
/sources/kolourpaint-25.12.0/commands/imagelib/transforms/kpTransformFlipCommand.cpp:111:62: error: expected ';' before '}' token
 111 |         doc->setImage(doc->image().mirrored(m_horiz, m_vert))
     |                                                              ^
     |                                                              ;
 112 | #endif
 113 |     }
     |     ~                                                        
make[2]: *** [CMakeFiles/kolourpaint.dir/build.make:289: CMakeFiles/kolourpaint.dir/commands/imagelib/transforms/kpTransformFlipCommand.cpp.o] Error 1
make[2]: *** Waiting for unfinished jobs....
make[1]: *** [CMakeFiles/Makefile2:221: CMakeFiles/kolourpaint.dir/all] Error 2
```

https://build.haiku-os.org/buildmaster/master/x86_64/logviewer.html?buildruns/13638/builds/86637.log
(cherry picked from commit 1ed34172dfb84e5abab29f01f1b026107bb619e3)